# Generated by Django 2.2.4 on 2020-02-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191025_1113'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
            ],
        ),
    ]
